class Player {
  constructor(){
    this.index = null;
    this.name = null;
    this.state=false;
    this.pokemon=null;
  }

  getCount(){
    var playerCountRef = database.ref('playerCount');
    playerCountRef.on("value",(data)=>{
      playerCount = data.val();
    })
  }

  getPlayer1Health(){
    database.ref('health1').on("value",(data)=>{
       player1Health = data.val();
    });
  }
  getPlayer1Attack(){
     database.ref('player1Attack').on("value",(data)=>{
         player1Attack=data.val();
     });
  }
  getPlayer2Attack(){
       database.ref('player2Attack').on("value",(data)=>{
         player2Attack=data.val();
       });
  }
  updatePlayer1Attack(data){
       database.ref('/').update({
          'player1Attack':data
       })
  }
  updatePlayer2Attack(data){
       database.ref('/').update({
          'player2Attack':data
       })
  }

  displayHealth(para1,para2){
    var y;
    if(para2===1){
      y=43
    } else{
      y=95
    }

    h1=createSprite(372,y,9,20);
    h2=createSprite(381,y,9,20);
    h3=createSprite(390,y,9,20);
    h4=createSprite(399,y,9,20);
    h5=createSprite(408,y,9,20);
    h6=createSprite(417,y,9,20);
    h7=createSprite(426,y,9,20);
    h8=createSprite(435,y,9,20);
    h9=createSprite(444,y,9,20);    
    h10=createSprite(453,y,9,20);
    h11=createSprite(462,y,9,20);
    h12=createSprite(471,y,9,20);
    h13=createSprite(480,y,9,20);
    h14=createSprite(489,y,9,20);
    h15=createSprite(498,y,9,20);
    h16=createSprite(507,y,9,20);
    h17=createSprite(516,y,9,20);
    h18=createSprite(525,y,9,20);
    h19=createSprite(534,y,9,20);
    h20=createSprite(543,y,9,20);

    var count=Math.round(para1/50);
    switch(count){
      case 0:h1.shapeColor="lightgreen";
             h2.shapeColor="red";
             h3.shapeColor="red";
             h4.shapeColor="red";
             h5.shapeColor="red";
             h6.shapeColor="red";
             h7.shapeColor="red";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 1:h1.shapeColor="lightgreen";
             h2.shapeColor="red";
             h3.shapeColor="red";
             h4.shapeColor="red";
             h5.shapeColor="red";
             h6.shapeColor="red";
             h7.shapeColor="red";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 2:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="red";
             h4.shapeColor="red";
             h5.shapeColor="red";
             h6.shapeColor="red";
             h7.shapeColor="red";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 3:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="red";
             h5.shapeColor="red";
             h6.shapeColor="red";
             h7.shapeColor="red";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 4:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="red";
             h6.shapeColor="red";
             h7.shapeColor="red";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 5:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="red";
             h7.shapeColor="red";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 6:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="red";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 7:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="red";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 8:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="red";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 9:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="red";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 10:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="red";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 11:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="red";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 12:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="red";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 13:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="red";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 14:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="lightgreen";
             h15.shapeColor="red";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 15:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="lightgreen";
             h15.shapeColor="lightgreen";
             h16.shapeColor="red";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 16:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="lightgreen";
             h15.shapeColor="lightgreen";
             h16.shapeColor="lightgreen";
             h17.shapeColor="red";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 17:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="lightgreen";
             h15.shapeColor="lightgreen";
             h16.shapeColor="lightgreen";
             h17.shapeColor="lightgreen";
             h18.shapeColor="red";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 18:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="lightgreen";
             h15.shapeColor="lightgreen";
             h16.shapeColor="lightgreen";
             h17.shapeColor="lightgreen";
             h18.shapeColor="lightgreen";
             h19.shapeColor="red";
             h20.shapeColor="red";
      break;
      case 19:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="lightgreen";
             h15.shapeColor="lightgreen";
             h16.shapeColor="lightgreen";
             h17.shapeColor="lightgreen";
             h18.shapeColor="lightgreen";
             h19.shapeColor="lightgreen";
             h20.shapeColor="red";
      break;
      case 20:h1.shapeColor="lightgreen";
             h2.shapeColor="lightgreen";
             h3.shapeColor="lightgreen";
             h4.shapeColor="lightgreen";
             h5.shapeColor="lightgreen";
             h6.shapeColor="lightgreen";
             h7.shapeColor="lightgreen";
             h8.shapeColor="lightgreen";
             h9.shapeColor="lightgreen";
             h10.shapeColor="lightgreen";
             h11.shapeColor="lightgreen";
             h12.shapeColor="lightgreen";
             h13.shapeColor="lightgreen";
             h14.shapeColor="lightgreen";
             h15.shapeColor="lightgreen";
             h16.shapeColor="lightgreen";
             h17.shapeColor="lightgreen";
             h18.shapeColor="lightgreen";
             h19.shapeColor="lightgreen";
             h20.shapeColor="lightgreen";
      break;


    }   
    
  }

  updatePlayer1Health(value){
    database.ref('/').update({
      'health1':value
    });
  }

  getPlayer2Health(){
    database.ref('health2').on("value",(data)=>{
       player2Health = data.val();
    });
  }

  updatePlayer2Health(value){
    database.ref('/').update({
       'health2':value
    });
  }
  

  updateCount(count){
    database.ref('/').update({
      playerCount: count
    });
  }

  update(){
    var playerIndex = "players/player" + this.index;
    database.ref(playerIndex).set({
      name:this.name,
      pokemon:this.pokemon
    });
  }

  static getPlayerInfo(){
    var playerInfoRef = database.ref('players');
    playerInfoRef.on("value",(data)=>{
      allPlayers = data.val();
    })
  }

  getCarsAtEnd(){
    database.ref('carsAtEnd').on("value",(data)=>{
        this.rank=data.val();
    })
  }

  static updateCarsAtEnd(rank){
      database.ref('/').update({'carsAtEnd':rank});
  }
}
